### ISSUE TITLE
Toolkit을 처음 써봤습니다.

### ISSUE THREAD

**Issue by ferrariRoma** [ferrariRoma/react_stargram#1]
로직이 괜찮은지 궁금합니다! 다른 피드백도 적극 수용하겠습니다. 🥹

**Comment by zubetcha** [comment]
안녕하세요!

redux-toolkit에서 작성하신 thunk나 reducer에서 크게 이상한 건 없는 것 같습니다!
다만 userSlice.js에서 FBloginAction 같은 경우는 따로 전역 상태에 사용되는 것처럼 보이지는 않는데요.
이렇게 redux의 state를 바꿔주는 게 아닌 경우에는 굳이 redux나 redux-toolkit을 사용할 필요는 없고,
컴포넌트에서 바로 호출해서 response를 활용하시는 게 좋습니다.

그리고 contentSlice.js에 있는 createContentAction, readContentAction, updateContentAction, deleteContentAction은 사용한 흔적이 안 보이네요..! 소스 코드 업데이트가 안 된 걸까요???

React의 마지막 심화 과정까지 오시느라 수고 많으셨습니다. 😊

**Comment by ferrariRoma** [comment]
@zubetcha 아 아뇨! 나태함에 급하게 배포를 한다고 안쓴 액션함수들을 지우지 못했습니다. 게으른 제자라 죄송합니다ㅜㅜ 앞으로는 더 열심히, 부지런히 해서 그런 부분들도 꼼꼼히 신경 쓸 수 있도록 하겠습니다!
부족한 점이 많은데도 격려해주셔서 감사합니다! 🙏
